spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project_1
    username: root
    password: Pa55w.rd

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
